import type { Professional, Review, Project } from './types'

export const professionals: Professional[] = [
  {
    id: '1',
    name: 'Juan Carlos Hernández',
    specialty: 'Electricista Industrial',
    rating: 4.9,
    reviewCount: 47,
    experience: 15,
    verified: true,
    licensed: true,
    zones: ['Polanco', 'Condesa', 'Roma'],
    responseTime: '2 horas',
    profileImage: '/professionals/electrician.jpg',
    portfolioCount: 34,
    description: 'Electricista certificado con más de 15 años de experiencia en instalaciones residenciales e industriales. Especializado en sistemas de iluminación LED, instalaciones de alta potencia y mantenimiento preventivo.',
    languages: ['Español', 'Inglés'],
    equipment: ['Equipo propio', 'Vehículo', 'Herramienta especializada'],
    hourlyRate: 450,
  },
  {
    id: '2',
    name: 'María González López',
    specialty: 'Albañil / Obra Civil',
    rating: 4.8,
    reviewCount: 63,
    experience: 12,
    verified: true,
    licensed: true,
    zones: ['Zapopan', 'Centro', 'Tlaquepaque'],
    responseTime: '3 horas',
    profileImage: '/professionals/mason.jpg',
    portfolioCount: 42,
    description: 'Especialista en construcción y remodelación de espacios. Trabajo con equipo propio de 5 personas para proyectos de cualquier escala.',
    languages: ['Español'],
    equipment: ['Equipo completo', 'Vehículo de carga', 'Andamios'],
    hourlyRate: 380,
  },
  {
    id: '3',
    name: 'Roberto Díaz Moreno',
    specialty: 'Fontanero Certificado',
    rating: 4.7,
    reviewCount: 89,
    experience: 8,
    verified: true,
    licensed: true,
    zones: ['San Pedro', 'Centro', 'Cumbres'],
    responseTime: '1 hora',
    profileImage: '/professionals/plumber.jpg',
    portfolioCount: 28,
    description: 'Fontanero profesional especializado en detección de fugas, instalación de sistemas de agua caliente y remodelación de baños.',
    languages: ['Español'],
    equipment: ['Detectores de fuga', 'Equipo de video inspección', 'Herramienta hidráulica'],
    hourlyRate: 400,
  },
  {
    id: '4',
    name: 'Carlos Mendoza Ruiz',
    specialty: 'Pintura Profesional',
    rating: 4.6,
    reviewCount: 52,
    experience: 10,
    verified: true,
    licensed: false,
    zones: ['Roma', 'Coyoacán', 'Del Valle'],
    responseTime: '4 horas',
    profileImage: '/professionals/painter.jpg',
    portfolioCount: 56,
    description: 'Pintor profesional con experiencia en acabados decorativos, texturas especiales y pintura exterior.',
    languages: ['Español'],
    equipment: ['Compresor', 'Pistola de pintura', 'Andamios'],
    hourlyRate: 320,
  },
  {
    id: '5',
    name: 'Ana Martínez Vega',
    specialty: 'Carpintería de Obra',
    rating: 4.9,
    reviewCount: 38,
    experience: 14,
    verified: true,
    licensed: true,
    zones: ['Santa Fe', 'Polanco', 'Lomas'],
    responseTime: '5 horas',
    profileImage: '/professionals/carpenter.jpg',
    portfolioCount: 67,
    description: 'Carpintera especializada en muebles a medida, cocinas integrales y closets. Trabajo con maderas finas y materiales de primera calidad.',
    languages: ['Español', 'Inglés'],
    equipment: ['Taller propio', 'CNC', 'Herramienta eléctrica completa'],
    hourlyRate: 500,
  },
  {
    id: '6',
    name: 'Luis Fernando Torres',
    specialty: 'HVAC / Climatización',
    rating: 4.5,
    reviewCount: 29,
    experience: 7,
    verified: true,
    licensed: true,
    zones: ['Centro', 'Condesa', 'Nápoles'],
    responseTime: '2 horas',
    profileImage: '/professionals/hvac.jpg',
    portfolioCount: 23,
    description: 'Técnico certificado en instalación y mantenimiento de sistemas de aire acondicionado, ventilación y calefacción.',
    languages: ['Español'],
    equipment: ['Equipo de diagnóstico', 'Herramienta especializada', 'Vehículo'],
    hourlyRate: 420,
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    professionalId: '1',
    clientId: 'c1',
    clientName: 'Patricia Ramírez',
    projectType: 'Instalación eléctrica cocina',
    ratings: {
      quality: 5,
      timeliness: 5,
      cleanliness: 5,
      communication: 5,
    },
    comment: 'Excelente trabajo. Juan Carlos fue muy profesional, llegó puntual y dejó todo impecable. La instalación quedó perfecta y me explicó todo el proceso.',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    professionalId: '1',
    clientId: 'c2',
    clientName: 'Miguel Ángel Soto',
    projectType: 'Remodelación eléctrica departamento',
    ratings: {
      quality: 5,
      timeliness: 4,
      cleanliness: 5,
      communication: 5,
    },
    comment: 'Muy buen trabajo, aunque tardó un día más de lo esperado por complicaciones en la obra. La calidad es impecable.',
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    professionalId: '2',
    clientId: 'c3',
    clientName: 'Laura Fernández',
    projectType: 'Ampliación de casa',
    ratings: {
      quality: 5,
      timeliness: 5,
      cleanliness: 4,
      communication: 5,
    },
    comment: 'María y su equipo hicieron un trabajo increíble. La ampliación quedó exactamente como la imaginamos. Muy recomendada.',
    createdAt: '2024-01-08',
  },
]

export const projects: Project[] = [
  {
    id: '1',
    clientId: 'c1',
    title: 'Instalación eléctrica en cocina nueva',
    description: 'Necesito instalar puntos de luz, contactos y conexión para estufa eléctrica en cocina que estoy remodelando. Aproximadamente 15m2.',
    type: 'Instalación eléctrica',
    budgetRange: '$10,000 - $25,000 MXN',
    location: 'CDMX - Condesa',
    status: 'published',
    createdAt: '2024-01-20',
  },
  {
    id: '2',
    clientId: 'c2',
    title: 'Reparación de fuga en baño principal',
    description: 'Tengo una fuga en el baño principal que está afectando el techo del piso de abajo. Necesito detección y reparación urgente.',
    type: 'Fontanería y drenaje',
    budgetRange: '$5,000 - $10,000 MXN',
    location: 'CDMX - Polanco',
    status: 'receiving_proposals',
    createdAt: '2024-01-19',
  },
]

export const testimonials = [
  {
    id: '1',
    name: 'Juan Pérez',
    project: 'Remodelación cocina',
    rating: 5,
    comment: 'Encontré al electricista perfecto en solo 2 días. El proceso fue súper sencillo y el trabajo quedó impecable.',
    image: '/testimonials/client1.jpg',
  },
  {
    id: '2',
    name: 'María Sánchez',
    project: 'Ampliación de casa',
    rating: 5,
    comment: 'La plataforma me ayudó a comparar presupuestos de 4 albañiles diferentes. Elegí el mejor y estoy muy satisfecha.',
    image: '/testimonials/client2.jpg',
  },
  {
    id: '3',
    name: 'Roberto García',
    project: 'Instalación HVAC',
    rating: 5,
    comment: 'El sistema de verificación me dio confianza para contratar. El técnico llegó con todo su equipo y terminó en tiempo récord.',
    image: '/testimonials/client3.jpg',
  },
]
